
services:
  influxdb:
    build: .
    container_name: influxtest
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    command: ["/sbin/init"]
    networks:
      - my_ipv6_network
    privileged: true
    ulimits:
      memlock:
        soft: -1
        hard: -1

  chronograf:
    image: chronograf:latest
    container_name: chronograf
    ports:
      - "8888:8888"
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
    networks:
      - my_ipv6_network

volumes:
  influxdb_data:

# networks:
#   influxdb_net:
#     driver: bridge

networks:
  my_ipv6_network:
    external: true
    name: my_ipv6_network

# networks:
#   mynetwork2:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: "192.168.100.0/24"
#         - subnet: "2001:db8:1::/64"