version: '3.8'

services:
  influxdb:
    image: lucamjdimarco/influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    networks:
      #- external_network
      external_network:
        ipv4_address: 10.89.0.30
        ipv6_address: fd00:dead:beef::30
    #command: ["influxd"]
    

  container1:
  # build:
  #     context: ./libbpf
  #     dockerfile: Dockerfile
    image: lucamjdimarco/ebpf-classifier:latest
    container_name: container1
    networks:
      #- external_network
      external_network:
        ipv4_address: 10.89.0.10
        ipv6_address: fd00:dead:beef::10
    privileged: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    #command: ["/sbin/init"]
    volumes:
      - ./start.sh:/usr/local/bin/init-script.sh
      - ./python-env.sh:/usr/local/bin/python-env.sh
    command: ["/bin/bash", "-c", "/usr/local/bin/init-script.sh && /sbin/init"]

  container2:
  # build:
  #     context: ./libbpf
  #     dockerfile: Dockerfile
    image: lucamjdimarco/ebpf-classifier:latest
    container_name: container2
    networks:
      #- external_network
      external_network:
        ipv4_address: 10.89.0.20
        ipv6_address: fd00:dead:beef::20
    privileged: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    #command: ["/sbin/init"]
    volumes:
      - ./start.sh:/usr/local/bin/init-script.sh
    command: ["/bin/bash", "-c", "/usr/local/bin/init-script.sh && /sbin/init"]
    
  chronograf:
    image: chronograf:latest
    container_name: chronograf
    ports:
      - "8888:8888"
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
    volumes:
      - ./chronograf-data:/var/lib/chronograf
    networks:
      #- external_network
      external_network:
        ipv4_address: 10.89.0.40
        ipv6_address: fd00:dead:beef::40
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      external_network:
        ipv4_address: 10.89.0.50
        ipv6_address: fd00:dead:beef::50
    command: ["redis-server"]

networks:
  external_network:
    external:
      name: my_ipv6_network
      #name: podman2
    ipam:
      config:
        - subnet: 10.89.0.0/24
          gateway: 10.89.0.1
        - subnet: fd00:dead:beef::/48
          gateway: fd00:dead:beef::1
