version: '3.8'

services:
  influxdb:
    image: lucamjdimarco/influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    networks:
      control_network:
        ipv4_address: 10.89.0.30
        ipv6_address: fd00:dead:beef::30
    cap_add:
      - NET_ADMIN
    volumes:
      - ./init_network.sh:/usr/local/bin/init_network.sh
    entrypoint: ["/bin/bash", "/usr/local/bin/init_network.sh", "influxd"]
    

  container1:
    image: lucamjdimarco/ebpf-classifier:latest
    container_name: container1
    networks:
      control_network:
        ipv4_address: 10.89.0.10
        ipv6_address: fd00:dead:beef::10

      data_network:
        ipv4_address: 10.90.0.10
        ipv6_address: fd01:dead:beef::10
    privileged: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./start.sh:/usr/local/bin/init-script.sh
      - ./python-env.sh:/usr/local/bin/python-env.sh
      - ./init_network.sh:/usr/local/bin/init_network.sh
    command: ["/bin/bash", "/usr/local/bin/init-script.sh", "/usr/local/bin/init-script.sh", /sbin/init"]

  container2:
    image: lucamjdimarco/ebpf-classifier:latest
    container_name: container2
    networks:
      control_network:
        ipv4_address: 10.89.0.20
        ipv6_address: fd00:dead:beef::20
      
      data_network:
        ipv4_address: 10.90.0.20
        ipv6_address: fd01:dead:beef::20
    privileged: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./start.sh:/usr/local/bin/init-script.sh
      - ./init_network.sh:/usr/local/bin/init_network.sh
    command: ["/bin/bash", "/usr/local/bin/init-script.sh", "/usr/local/bin/init-script.sh", /sbin/init"]
    
  chronograf:
    image: chronograf:latest
    container_name: chronograf
    ports:
      - "8888:8888"
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
    volumes:
      - ./chronograf-data:/var/lib/chronograf
    networks:
      control_network:
        ipv4_address: 10.89.0.40
        ipv6_address: fd00:dead:beef::40
    cap_add:
      - NET_ADMIN
    volumes:
      - ./init_network.sh:/usr/local/bin/init_network.sh
    entrypoint: ["/bin/bash", "/usr/local/bin/init_network.sh", "chronograf"]
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      control_network:
        ipv4_address: 10.89.0.50
        ipv6_address: fd00:dead:beef::50
    command: ["redis-server"]

networks:
  control_network:
    external:
      name: control_network
    ipam:
      config:
        - subnet: 10.89.0.0/24
          gateway: 10.89.0.1
        - subnet: fd00:dead:beef::/48
          gateway: fd00:dead:beef::1
  
  data_network:
    external:
      name: data_network
    ipam:
      config:
        - subnet: 10.10.0.0/24
          gateway: 10.90.0.1
        - subnet: fd01:dead:beef::/48
          gateway: fd01:dead:beef::1
  
