
# services:
#   influxdb:
#     build: .
#     container_name: influxtest
#     ports:
#       - "8086:8086"
#     volumes:
#       - influxdb_data:/var/lib/influxdb
#     command: ["/sbin/init"]
#     networks:
#       - my_ipv6_network
#     privileged: true
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1

#   chronograf:
#     image: chronograf:latest
#     container_name: chronograf
#     ports:
#       - "8888:8888"
#     depends_on:
#       - influxdb
#     environment:
#       - INFLUXDB_URL=http://influxdb:8086
#     networks:
#       - my_ipv6_network

# volumes:
#   influxdb_data:

# # networks:
# #   influxdb_net:
# #     driver: bridge

# networks:
#   my_ipv6_network:
#     external: true
#     name: my_ipv6_network

# # networks:
# #   mynetwork2:
# #     driver: bridge
# #     ipam:
# #       config:
# #         - subnet: "192.168.100.0/24"
# #         - subnet: "2001:db8:1::/64"

version: '3.8'

services:
  influxdb:
  # build:
  #     context: ./libbpf
  #     dockerfile: Dockerfile
    image: lucamjdimarco/podman-influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    networks:
      #- external_network
      external_network:
        ipv4_address: 10.89.0.30
        ipv6_address: fd00:dead:beef::30
    command: ["influxd"]
    

  libbpf1:
  # build:
  #     context: ./libbpf
  #     dockerfile: Dockerfile
    image: lucamjdimarco/podman-influxdb:latest
    container_name: libbpf1
    networks:
      #- external_network
      external_network:
        ipv4_address: 10.89.0.10
        ipv6_address: fd00:dead:beef::10
    privileged: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    #command: ["/sbin/init"]
    volumes:
      - ./start.sh:/usr/local/bin/init-script.sh
    command: ["/bin/bash", "-c", "/usr/local/bin/init-script.sh && /sbin/init"]

  libbpf2:
  # build:
  #     context: ./libbpf
  #     dockerfile: Dockerfile
    image: lucamjdimarco/podman-influxdb:latest
    container_name: libbpf2
    networks:
      #- external_network
      external_network:
        ipv4_address: 10.89.0.20
        ipv6_address: fd00:dead:beef::20
    privileged: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    #command: ["/sbin/init"]
    volumes:
      - ./start.sh:/usr/local/bin/init-script.sh
    command: ["/bin/bash", "-c", "/usr/local/bin/init-script.sh && /sbin/init"]
    
  chronograf:
    image: chronograf:latest
    container_name: chronograf
    ports:
      - "8888:8888"
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
    volumes:
      - ./chronograf-data:/var/lib/chronograf
    networks:
      #- external_network
      external_network:
        ipv4_address: 10.89.0.40
        ipv6_address: fd00:dead:beef::40

networks:
  external_network:
    external:
      name: my_ipv6_network
      #name: podman2
    ipam:
      config:
        - subnet: 10.89.0.0/24
          gateway: 10.89.0.1
        - subnet: fd00:dead:beef::/48
          gateway: fd00:dead:beef::1
